### ISSUE TITLE
Bug Fixes and dependency updates

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-newsletter-builder#16]
### Description

<strike>Create adapter for sending emails through Omeda.</strike>

We no longer need the Omeda integration so this this branch only aims now to update npm dependencies and it also includes several other bug fixes we will need in the plugin regardless.

### Use Case

<strike>A user should be able to send emails through Omeda</strike>

- Updates PHP, node, npm, @wordpress/scripts
- Fixes various notices and warnings.

**Comment by attackant** [comment]
Done in #112
