### ISSUE TITLE
Sendgrid Adapter (Lede)

### ISSUE THREAD

**Issue by ostowe** [alleyinteractive/wp-newsletter-builder#25]
### Description

Note: the intent so far is for the Lede development to work on this ticket. For those with access to Athena, here is the ticket: https://getscrum.app/projects/15/stories/13731.

The Lede platform uses Sendgrid as its ESP, and therefore the ESP all publishers on the platform must use as well. We need an adapter for the Newsletter Builder for Sendgrid to make this work seamlessly.

### Use Case

Publishers on Lede will need to be able to do the following, which roughly correspond do the options in the [Single Send](https://docs.sendgrid.com/ui/sending-email/single-sends) functionality in Sendgrid:
* Email subject
* Multi-select of contact lists OR contact segments to which a newsletter will be delivered from among the lists defined in Sendgrid.
* Multi-select of contact lists OR contact segments to exclude from the newsletter delivery (this is probably a nice-to-have).
* Scheduling (when to send the email).
* Select an unsubscribe group for the newsletter. This selection will dictate two things:
  * A list of users that will be excluded from the delivery of this newsletter.
  * The unsubscribe group a user will be added to if they click the "unsubscribe" button in the newsletter footer.

**Comment by mogmarsh** [comment]
Adding comments to preserve the original description, but I think the last item should be

- Select an unsubscribe group for the newsletter. This selection will dictate a list of users that will be excluded from the delivery of this newsletter.
- Provide an unsubscribe link for the message (sendgrid may have a special way to support this. I'm not sure yet)

**Comment by mogmarsh** [comment]
Note that there is already an interface for an Email Provider adapter. Only one adapter exists so far, so adding a second one may identify some functionality that must be handled in the adapter instead of the core plugin. In that case, the functionality should be added to the interface, and all existing adapters (currently one).
